# Redis configuration
REDIS_HOST=judge0-redis
REDIS_PORT=6379

# PostgreSQL configuration
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0

# System configuration
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
ENABLE_WAIT_RESULT=true

# Auth token (empty to disable API authentication)
AUTHN_TOKEN=
