CREATE DATABASE IF NOT EXISTS code_judge_mvp;
USE code_judge_mvp;

CREATE TABLE IF NOT EXISTS problems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  difficulty VARCHAR(32) NOT NULL DEFAULT 'Easy',
  topic VARCHAR(128) NOT NULL DEFAULT 'General',
  constraints_text TEXT NULL,
  image_url TEXT NULL,
  is_practice BOOLEAN NOT NULL DEFAULT TRUE,
  official_solution TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS testcases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  problem_id INT NOT NULL,
  input_data TEXT NOT NULL,
  expected_output TEXT NOT NULL,
  visibility VARCHAR(16) NOT NULL DEFAULT 'visible',
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_testcases_problem
    FOREIGN KEY (problem_id)
    REFERENCES problems(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(64) NOT NULL DEFAULT 'Contestant',
  password_hash VARCHAR(255) NOT NULL,
  valid_till DATE NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'Active',
  submissions_count INT NOT NULL DEFAULT 0,
  acceptance_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  contests_count INT NOT NULL DEFAULT 0,
  last_activity VARCHAR(128) NOT NULL DEFAULT 'Just now',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contest_name VARCHAR(255) NOT NULL,
  contest_code VARCHAR(64) NOT NULL UNIQUE,
  description TEXT NULL,
  start_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_date DATE NOT NULL,
  end_time TIME NOT NULL,
  duration VARCHAR(64) NOT NULL,
  visibility VARCHAR(32) NOT NULL DEFAULT 'Public',
  access_control VARCHAR(64) NOT NULL DEFAULT 'Allowed Users',
  allowed_users TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'Upcoming',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contest_problems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contest_id INT NOT NULL,
  problem_id INT NOT NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'existing',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_contest_problems_contest
    FOREIGN KEY (contest_id)
    REFERENCES contests(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_contest_problems_problem
    FOREIGN KEY (problem_id)
    REFERENCES problems(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contest_participants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contest_id INT NOT NULL,
  user_id INT NOT NULL,
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_contest_participants_contest
    FOREIGN KEY (contest_id)
    REFERENCES contests(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_contest_participants_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,
  UNIQUE KEY uniq_contest_participant (contest_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(64) NOT NULL,
  event VARCHAR(255) NOT NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'Info',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  problem_id INT NOT NULL,
  code TEXT NOT NULL,
  language_id INT NOT NULL,
  verdict VARCHAR(64) NOT NULL,
  passed_count INT NOT NULL DEFAULT 0,
  total_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_submissions_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_submissions_problem
    FOREIGN KEY (problem_id)
    REFERENCES problems(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


